### ISSUE TITLE
放到这里来干嘛？

### ISSUE THREAD

**Issue by iusn** [zhangsen093725/ZSImagePickerController#2]

**Comment by zhangsen093725** [comment]
抱歉， 最近项目太忙，暂时没办法更新。
还有一点需要说明一下，虽说GitHub是开源平台，但是请问你这句话的意思是什么呢？在README中已经声明，这次提交的静态库是我自己在造轮子，也是帮助自己记录进度使用的，为啥不能放到GitHub呢？与其找别人的轮子不如自己造轮子，适合自己的才是最好的。

**Comment by DragonMr** [comment]
怎么没有获取到选中图片的方法啊。就是  取出选中图片 这个方法 ，这个你里面就没有写么 只是多选 没什么用处呐
